# Generated by Django 2.2 on 2021-03-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoiceid',
            field=models.ForeignKey(db_column='InvoiceId', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Invoices'),
        ),
    ]
